/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func (s *Server) getUePolicyRoutes() []Route {
	return []Route{
		{
			Method:  http.MethodDelete,
			Pattern: "/policies/{polAssoId}",
			APIFunc: s.PoliciesPolAssoIdDelete,
		},
		{
			Method:  http.MethodGet,
			Pattern: "/policies/{polAssoId}",
			APIFunc: s.PoliciesPolAssoIdGet,
		},
		{
			Method:  http.MethodPost,
			Pattern: "/policies/{polAssoId}/update",
			APIFunc: s.PoliciesPolAssoIdUpdatePost,
		},
		{
			Method:  http.MethodPost,
			Pattern: "/policies",
			APIFunc: s.PoliciesPost,
		},
	}
}

// PoliciesPolAssoIdDelete -
func (s *Server) PoliciesPolAssoIdDelete(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, nil)
}

// PoliciesPolAssoIdGet -
func (s *Server) PoliciesPolAssoIdGet(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, nil)
}

// PoliciesPolAssoIdUpdatePost -
func (s *Server) PoliciesPolAssoIdUpdatePost(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, nil)
}

// PoliciesPost -
func (s *Server) PoliciesPost(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, nil)
}
